# Generated by Django 3.1.3 on 2020-11-08 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.TextField()),
                ('expiration_date', models.DateField(auto_now_add=True)),
                ('ingredient_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ingredient.ingredient')),
            ],
        ),
    ]
